openapi: 3.1.0
info:
  title: Meta Marketing API
  description: |
    Meta Marketing API for campaign management and insights.
    Rate limits and best practices are enforced.
  version: '22.0'
  x-rate-limiting:
    standard-tier:
      points: 9000
      window: 300
      block: 60
    development-tier:
      points: 60
      window: 300
      block: 300
  x-performance:
    cache-ttl: 300
    timeout:
      sync: 30
      async: 3600
    compression: true
    batch-size: 100

servers:
  - url: https://graph.facebook.com/v22.0
    description: Meta Graph API v22.0

security:
  - bearerAuth: []

paths:
  /102264027940184:
    get:
      operationId: getPageAccessToken
      summary: Get page access token
      description: Retrieve a page access token for the specified page ID
      tags:
        - Authentication
      parameters:
        - $ref: "./paths/getPageAccessToken.yaml#/parameters/access_token"
      responses:
        $ref: "./paths/getPageAccessToken.yaml#/responses"

  /act_{account_id}/campaigns:
    get:
      operationId: getCampaigns
      summary: List campaigns
      description: Get a list of all campaigns for the specified ad account
      tags:
        - Campaigns
      parameters:
        - $ref: "./paths/getCampaigns.yaml#/parameters/account_id"
        - $ref: "./paths/getCampaigns.yaml#/parameters/access_token"
        - $ref: "./paths/getCampaigns.yaml#/parameters/fields"
        - $ref: "./paths/getCampaigns.yaml#/parameters/limit"
        - $ref: "./paths/getCampaigns.yaml#/parameters/after"
      responses:
        $ref: "./paths/getCampaigns.yaml#/responses"

  /act_{account_id}/campaigns/{campaign_id}:
    get:
      operationId: getCampaignById
      summary: Get campaign details
      description: Get detailed information about a specific campaign
      tags:
        - Campaigns
      parameters:
        - $ref: "./paths/getCampaignById.yaml#/parameters/account_id"
        - $ref: "./paths/getCampaignById.yaml#/parameters/campaign_id"
        - $ref: "./paths/getCampaignById.yaml#/parameters/access_token"
        - $ref: "./paths/getCampaignById.yaml#/parameters/fields"
      responses:
        $ref: "./paths/getCampaignById.yaml#/responses"

  /act_{account_id}/campaigns/{campaign_id}/insights:
    get:
      operationId: getCampaignInsights
      summary: Get campaign insights
      description: Get performance metrics for a specific campaign
      tags:
        - Insights
      parameters:
        - $ref: "./paths/getCampaignInsights.yaml#/parameters/account_id"
        - $ref: "./paths/getCampaignInsights.yaml#/parameters/campaign_id"
        - $ref: "./paths/getCampaignInsights.yaml#/parameters/access_token"
        - $ref: "./paths/getCampaignInsights.yaml#/parameters/fields"
        - $ref: "./paths/getCampaignInsights.yaml#/parameters/date_preset"
        - $ref: "./paths/getCampaignInsights.yaml#/parameters/time_increment"
      responses:
        $ref: "./paths/getCampaignInsights.yaml#/responses"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Meta API Access Token

  headers:
    BusinessUseCaseUsage:
      description: Business use case usage information
      schema:
        type: string
    RateLimitReset:
      description: Time until rate limit reset in seconds
      schema:
        type: integer
    CacheControl:
      description: Cache control directives
      schema:
        type: string

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Unauthorized:
      description: Invalid or missing access token
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    RateLimitExceeded:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
            type:
              type: string
    PageToken:
      type: object
      properties:
        access_token:
          type: string
          description: Page access token
    Campaign:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum: [ACTIVE, PAUSED, DELETED]
        objective:
          type: string
          enum: [LINK_CLICKS, POST_ENGAGEMENT, VIDEO_VIEWS]
    CampaignList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Campaign"
        paging:
          type: object
          properties:
            cursors:
              type: object
              properties:
                before:
                  type: string
                after:
                  type: string
    InsightsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              impressions:
                type: integer
              reach:
                type: integer
              spend:
                type: number
              inline_post_engagement:
                type: integer
              video_p25_watched_actions:
                type: integer
              video_p50_watched_actions:
                type: integer
              video_p75_watched_actions:
                type: integer
              video_p95_watched_actions:
                type: integer
              video_avg_time_watched_actions:
                type: number
