openapi: 3.1.0
info:
  title: Meta Marketing API
  description: |
    Meta Marketing API for campaign management and insights.
    Rate limits and best practices are enforced.

    # Internal Configuration
    The connector uses these pre-configured values:
    - Page ID: 102264027940184
    - Ad Account ID: 906594379912215 (without act_ prefix)
    - Campaign ID: 23847392874

    # Authentication Flow
    1. User Bearer Token (stored in connector)
    2. Page Token Generation:
       - Uses stored bearer token
       - Calls /me/accounts internally
       - Caches page token for 1 hour
  version: '22.0'
  x-connector-config:
    page-id: "102264027940184"
    ad-account-id: "906594379912215"
    token-cache-duration: 3600
    required-permissions:
      - manage_pages
      - ads_management
      - ads_read
  x-rate-limiting:
    standard-tier:
      points: 9000
      window: 300
      block: 60
    development-tier:
      points: 60
      window: 300
      block: 300
  x-performance:
    cache-ttl: 300
    timeout:
      sync: 30
      async: 3600
    compression: true
    batch-size: 100

servers:
  - url: https://graph.facebook.com/v22.0
    description: Meta Graph API v22.0

security:
  - bearerAuth: []

paths:
  /me/accounts:
    get:
      operationId: getPageAccounts
      summary: Get page accounts
      description: |
        Internal endpoint to generate page access token.
        Called automatically by the connector using stored bearer token.
      tags:
        - Authentication
      parameters:
        - name: access_token
          in: query
          required: true
          description: User access token with manage_pages permission
          schema:
            type: string
        - name: fields
          in: query
          required: true
          description: Fields to return
          schema:
            type: string
            default: "id,name,access_token"
      responses:
        '200':
          description: Success. Returns page access token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageAccountList"
              example:
                data:
                  - id: "102264027940184"
                    name: "Test Page"
                    access_token: "EAAJKpXyZB8i0BADHkZAkHrZBTZAZAQZDZD"

  /act_{account_id}/campaigns:
    get:
      operationId: getCampaigns
      summary: List campaigns
      description: |
        Get a list of all campaigns for the specified ad account.
        Uses pre-configured account_id (906594379912215).
      tags:
        - Campaigns
      parameters:
        - name: account_id
          in: path
          required: true
          description: Ad account ID (without act_ prefix)
          schema:
            type: string
            pattern: '^\d+$'
            example: "906594379912215"
        - name: access_token
          in: query
          required: true
          description: Page access token (generated automatically)
          schema:
            type: string
        - name: fields
          in: query
          required: true
          description: Comma-separated list of fields to return
          schema:
            type: string
            default: "id,name,status,objective"
        - name: limit
          in: query
          description: Number of records to return per request
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 25
        - name: after
          in: query
          description: Cursor for pagination
          schema:
            type: string
      responses:
        '200':
          description: Success. Returns a list of campaigns
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CampaignList"
              example:
                data:
                  - id: "23847392874"
                    name: "Website Traffic Campaign"
                    status: "ACTIVE"
                    objective: "LINK_CLICKS"

  /act_{account_id}/campaigns/{campaign_id}:
    get:
      operationId: getCampaignById
      summary: Get campaign details
      description: |
        Get detailed information about a specific campaign.
        Uses pre-configured account_id (906594379912215).
      tags:
        - Campaigns
      parameters:
        - name: account_id
          in: path
          required: true
          description: Ad account ID (without act_ prefix)
          schema:
            type: string
            pattern: '^\d+$'
            example: "906594379912215"
        - name: campaign_id
          in: path
          required: true
          description: Campaign ID to retrieve details for
          schema:
            type: string
            example: "23847392874"
        - name: access_token
          in: query
          required: true
          description: Page access token (generated automatically)
          schema:
            type: string
        - name: fields
          in: query
          required: true
          description: Comma-separated list of fields to return
          schema:
            type: string
            default: "id,name,status,objective"
      responses:
        '200':
          description: Success. Returns detailed campaign information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Campaign"
              example:
                id: "23847392874"
                name: "Website Traffic Campaign"
                status: "ACTIVE"
                objective: "LINK_CLICKS"

  /act_{account_id}/campaigns/{campaign_id}/insights:
    get:
      operationId: getCampaignInsights
      summary: Get campaign insights
      description: |
        Get performance metrics for a specific campaign.
        Uses pre-configured account_id (906594379912215).
      tags:
        - Insights
      parameters:
        - name: account_id
          in: path
          required: true
          description: Ad account ID (without act_ prefix)
          schema:
            type: string
            pattern: '^\d+$'
            example: "906594379912215"
        - name: campaign_id
          in: path
          required: true
          description: Campaign ID to retrieve insights for
          schema:
            type: string
            example: "23847392874"
        - name: access_token
          in: query
          required: true
          description: Page access token (generated automatically)
          schema:
            type: string
        - name: fields
          in: query
          required: true
          description: List of metrics to return
          schema:
            type: array
            items:
              type: string
              enum:
                - impressions
                - reach
                - spend
                - inline_post_engagement
                - video_p25_watched_actions
                - video_p50_watched_actions
                - video_p75_watched_actions
                - video_p95_watched_actions
                - video_avg_time_watched_actions
            default:
              - impressions
              - reach
              - spend
        - name: date_preset
          in: query
          description: Predefined date range for the report
          schema:
            type: string
            enum:
              - today
              - yesterday
              - this_month
              - last_month
              - this_quarter
              - lifetime
            default: "last_month"
        - name: time_increment
          in: query
          description: Group results by N days
          schema:
            type: integer
            enum: [1, 7, 28]
            default: 1
      responses:
        '200':
          description: Success. Returns campaign performance metrics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InsightsResponse"
              example:
                data:
                  - date_start: "2025-03-01"
                    date_end: "2025-03-01"
                    impressions: 1234
                    reach: 987
                    spend: 50.25

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        User access token stored in connector.
        Used internally to generate page access token.

  headers:
    BusinessUseCaseUsage:
      description: Business use case usage information
      schema:
        type: string
    RateLimitReset:
      description: Time until rate limit reset in seconds
      schema:
        type: integer
    CacheControl:
      description: Cache control directives
      schema:
        type: string

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Unauthorized:
      description: Invalid or missing access token
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    RateLimitExceeded:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
            type:
              type: string
    PageToken:
      type: object
      properties:
        access_token:
          type: string
          description: Page access token
    Campaign:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum: [ACTIVE, PAUSED, DELETED]
        objective:
          type: string
          enum: [LINK_CLICKS, POST_ENGAGEMENT, VIDEO_VIEWS]
    CampaignList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Campaign"
        paging:
          type: object
          properties:
            cursors:
              type: object
              properties:
                before:
                  type: string
                after:
                  type: string
    InsightsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              impressions:
                type: integer
              reach:
                type: integer
              spend:
                type: number
              inline_post_engagement:
                type: integer
              video_p25_watched_actions:
                type: integer
              video_p50_watched_actions:
                type: integer
              video_p75_watched_actions:
                type: integer
              video_p95_watched_actions:
                type: integer
              video_avg_time_watched_actions:
                type: number
    AdAccountList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/AdAccount"
        paging:
          type: object
          properties:
            cursors:
              type: object
              properties:
                before:
                  type: string
                after:
                  type: string
    AdAccount:
      type: object
      properties:
        account_id:
          type: string
          description: Ad account ID
          example: "906594379912215"
        name:
          type: string
          description: Ad account name
          example: "Main Ad Account"
        account_status:
          type: string
          description: Account status
          enum: [ACTIVE, DISABLED, UNSETTLED, PENDING_RISK_REVIEW, PENDING_SETTLEMENT, IN_GRACE_PERIOD, PENDING_CLOSURE, CLOSED, ANY_ACTIVE, ANY_CLOSED]
          example: "ACTIVE"
        business_name:
          type: string
          description: Business name
          example: "My Business"
        currency:
          type: string
          description: Account currency
          example: "USD"
    PageAccountList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/PageAccount"
        paging:
          $ref: "#/components/schemas/Paging"
    PageAccount:
      type: object
      properties:
        id:
          type: string
          description: Page ID
          example: "102264027940184"
        name:
          type: string
          description: Page name
          example: "Test Page"
        access_token:
          type: string
          description: Page access token
          example: "EAAJKpXyZB8i0BADHkZAkHrZBTZAZAQZDZD"
    Paging:
      type: object
      properties:
        cursors:
          type: object
          properties:
            before:
              type: string
              example: "MAZDZD"
            after:
              type: string
              example: "MQZDZD"
