openapi: 3.1.0
info:
  title: Meta Marketing API
  description: |
    Meta Marketing API for campaign management and insights.
    Rate limits and best practices are enforced.
  version: '22.0'
  x-rate-limiting:
    standard-tier:
      points: 9000
      window: 300
      block: 60
    development-tier:
      points: 60
      window: 300
      block: 300
  x-performance:
    cache-ttl: 300
    timeout:
      sync: 30
      async: 3600
    compression: true
    batch-size: 100

servers:
  - url: https://graph.facebook.com/v22.0
    description: Meta Graph API v22.0

security:
  - bearerAuth: []

paths:
  /102264027940184:
    get:
      operationId: getPageAccessToken
      summary: Get page access token
      description: Retrieve a page access token for the specified page ID
      tags:
        - Authentication
      parameters:
        - name: access_token
          in: query
          required: true
          description: User access token with manage_pages permission
          schema:
            type: string
      responses:
        '200':
          description: Success. Returns a long-lived page access token
          headers:
            X-Business-Use-Case-Usage:
              $ref: "#/components/headers/BusinessUseCaseUsage"
            X-Rate-Limit-Reset:
              $ref: "#/components/headers/RateLimitReset"
            Cache-Control:
              $ref: "#/components/headers/CacheControl"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageToken"
              example:
                access_token: "EAAJKpXyZB8i0BADHkZAkHrZBTZAZAQZDZD"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/Unauthorized"
        '429':
          $ref: "#/components/responses/RateLimitExceeded"

  /act_{account_id}/campaigns:
    get:
      operationId: getCampaigns
      summary: List campaigns
      description: Get a list of all campaigns for the specified ad account
      tags:
        - Campaigns
      parameters:
        - name: account_id
          in: path
          required: true
          description: Ad account ID (act_906594379912215)
          schema:
            type: string
            pattern: '^act_\d+$'
            example: "act_906594379912215"
        - name: access_token
          in: query
          required: true
          description: Page access token with ads_management permission
          schema:
            type: string
        - name: fields
          in: query
          required: true
          description: Comma-separated list of fields to return
          schema:
            type: string
            example: "id,name,status,objective"
        - name: limit
          in: query
          description: Number of records to return per request
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 25
        - name: after
          in: query
          description: Cursor for pagination
          schema:
            type: string
      responses:
        '200':
          description: Success. Returns a list of campaigns
          headers:
            X-Business-Use-Case-Usage:
              $ref: "#/components/headers/BusinessUseCaseUsage"
            X-Rate-Limit-Reset:
              $ref: "#/components/headers/RateLimitReset"
            Cache-Control:
              $ref: "#/components/headers/CacheControl"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CampaignList"
              example:
                data:
                  - id: "23847392874"
                    name: "Website Traffic Campaign"
                    status: "ACTIVE"
                    objective: "LINK_CLICKS"
                paging:
                  cursors:
                    before: "MAZDZD"
                    after: "MQZDZD"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/Unauthorized"
        '429':
          $ref: "#/components/responses/RateLimitExceeded"

  /act_{account_id}/campaigns/{campaign_id}:
    get:
      operationId: getCampaignById
      summary: Get campaign details
      description: Get detailed information about a specific campaign
      tags:
        - Campaigns
      parameters:
        - name: account_id
          in: path
          required: true
          description: Ad account ID (act_906594379912215)
          schema:
            type: string
            pattern: '^act_\d+$'
            example: "act_906594379912215"
        - name: campaign_id
          in: path
          required: true
          description: Campaign ID to retrieve details for
          schema:
            type: string
            example: "23847392874"
        - name: access_token
          in: query
          required: true
          description: Page access token with ads_management permission
          schema:
            type: string
        - name: fields
          in: query
          required: true
          description: Comma-separated list of fields to return
          schema:
            type: string
            example: "id,name,status,objective"
      responses:
        '200':
          description: Success. Returns detailed campaign information
          headers:
            X-Business-Use-Case-Usage:
              $ref: "#/components/headers/BusinessUseCaseUsage"
            X-Rate-Limit-Reset:
              $ref: "#/components/headers/RateLimitReset"
            Cache-Control:
              $ref: "#/components/headers/CacheControl"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Campaign"
              example:
                id: "23847392874"
                name: "Website Traffic Campaign"
                status: "ACTIVE"
                objective: "LINK_CLICKS"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/Unauthorized"
        '429':
          $ref: "#/components/responses/RateLimitExceeded"

  /act_{account_id}/campaigns/{campaign_id}/insights:
    get:
      operationId: getCampaignInsights
      summary: Get campaign insights
      description: Get performance metrics for a specific campaign
      tags:
        - Insights
      parameters:
        - name: account_id
          in: path
          required: true
          description: Ad account ID (act_906594379912215)
          schema:
            type: string
            pattern: '^act_\d+$'
            example: "act_906594379912215"
        - name: campaign_id
          in: path
          required: true
          description: Campaign ID to retrieve insights for
          schema:
            type: string
            example: "23847392874"
        - name: access_token
          in: query
          required: true
          description: Page access token with ads_read permission
          schema:
            type: string
        - name: fields
          in: query
          required: true
          description: List of metrics to return
          schema:
            type: array
            items:
              type: string
              enum:
                - impressions
                - reach
                - spend
                - inline_post_engagement
                - video_p25_watched_actions
                - video_p50_watched_actions
                - video_p75_watched_actions
                - video_p95_watched_actions
                - video_avg_time_watched_actions
        - name: date_preset
          in: query
          description: Predefined date range for the report
          schema:
            type: string
            enum:
              - today
              - yesterday
              - this_month
              - last_month
              - this_quarter
              - lifetime
            default: "last_month"
        - name: time_increment
          in: query
          description: Group results by N days
          schema:
            type: integer
            enum: [1, 7, 28]
            default: 1
      responses:
        '200':
          description: Success. Returns campaign performance metrics
          headers:
            X-Business-Use-Case-Usage:
              $ref: "#/components/headers/BusinessUseCaseUsage"
            X-Rate-Limit-Reset:
              $ref: "#/components/headers/RateLimitReset"
            Cache-Control:
              $ref: "#/components/headers/CacheControl"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InsightsResponse"
              example:
                data:
                  - date_start: "2025-03-01"
                    date_end: "2025-03-01"
                    impressions: 1234
                    reach: 987
                    spend: 50.25
                    inline_post_engagement: 45
                    video_p25_watched_actions: 800
                    video_p50_watched_actions: 600
                    video_p75_watched_actions: 400
                    video_p95_watched_actions: 200
                    video_avg_time_watched_actions: 15.5
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/Unauthorized"
        '429':
          $ref: "#/components/responses/RateLimitExceeded"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Meta API Access Token

  headers:
    BusinessUseCaseUsage:
      description: Business use case usage information
      schema:
        type: string
    RateLimitReset:
      description: Time until rate limit reset in seconds
      schema:
        type: integer
    CacheControl:
      description: Cache control directives
      schema:
        type: string

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Unauthorized:
      description: Invalid or missing access token
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    RateLimitExceeded:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
            type:
              type: string
    PageToken:
      type: object
      properties:
        access_token:
          type: string
          description: Page access token
    Campaign:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum: [ACTIVE, PAUSED, DELETED]
        objective:
          type: string
          enum: [LINK_CLICKS, POST_ENGAGEMENT, VIDEO_VIEWS]
    CampaignList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Campaign"
        paging:
          type: object
          properties:
            cursors:
              type: object
              properties:
                before:
                  type: string
                after:
                  type: string
    InsightsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              impressions:
                type: integer
              reach:
                type: integer
              spend:
                type: number
              inline_post_engagement:
                type: integer
              video_p25_watched_actions:
                type: integer
              video_p50_watched_actions:
                type: integer
              video_p75_watched_actions:
                type: integer
              video_p95_watched_actions:
                type: integer
              video_avg_time_watched_actions:
                type: number
