openapi: 3.1.0
info:
  title: Meta Marketing API Connector
  description: |
    API to access Meta v22.0 marketing campaigns and insights.
    Rate Limits:
    - Standard tier: 9000 points/300s (read=1pt, write=3pts)
    - Development tier: 60 points/300s
    Performance:
    - Use date filters to reduce query size
    - Request unique metrics separately
    - Cache responses for 5 minutes
  version: '1.4.0'
  x-rate-limiting:
    standard-tier:
      points: 9000
      window: 300
      block: 60
    development-tier:
      points: 60
      window: 300
      block: 300
  x-performance:
    cache-ttl: 300
    timeout:
      sync: 30
      async: 3600
    compression: true
    batch-size: 100

servers:
  - url: https://graph.facebook.com/v22.0
    description: Meta Graph API v22.0

security:
  - BearerAuth: []

paths:
  /102264027940184:
    $ref: "https://raw.githubusercontent.com/danielduartefilho/meta-marketing-api/master/paths/getPageAccessToken.yaml"
  /act_906594379912215/campaigns:
    $ref: "https://raw.githubusercontent.com/danielduartefilho/meta-marketing-api/master/paths/getCampaigns.yaml"
  /{campaign_id}:
    $ref: "https://raw.githubusercontent.com/danielduartefilho/meta-marketing-api/master/paths/getCampaignById.yaml"
  /act_906594379912215/insights:
    $ref: "https://raw.githubusercontent.com/danielduartefilho/meta-marketing-api/master/paths/getCampaignInsights.yaml"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  headers:
    $ref: "https://raw.githubusercontent.com/danielduartefilho/meta-marketing-api/master/components/headers.yaml"

  responses:
    $ref: "https://raw.githubusercontent.com/danielduartefilho/meta-marketing-api/master/components/responses.yaml"

  schemas:
    $ref: "https://raw.githubusercontent.com/danielduartefilho/meta-marketing-api/master/components/schemas.yaml"
