openapi: 3.1.0
info:
  title: Meta Marketing API
  version: '22.0'
  description: |
    Meta Marketing API para análise de performance de anúncios.
    Requer permissões: ads_read, ads_management_read_only, pages_read_engagement

servers:
  - url: https://graph.facebook.com/v22.0
    description: Meta Graph API v22.0

security:
  - bearerAuth: []

paths:
  /me/accounts:
    get:
      operationId: getAccounts
      summary: Lista páginas disponíveis
      description: Retorna a lista de páginas que o usuário tem acesso
      responses:
        '200':
          description: Success. Retorna página Wiemspro Brasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "102264027940184"
                        name:
                          type: string
                          example: "Wiemspro Brasil"
        '401':
          $ref: "#/components/responses/Unauthorized"
        '429':
          $ref: "#/components/responses/RateLimitExceeded"

  /act_{account_id}/insights:
    get:
      operationId: getInsights
      summary: Métricas de performance
      description: |
        Retorna métricas de performance para a conta.
        Suporta breakdowns por formato e demografia.
      parameters:
        - name: account_id
          in: path
          required: true
          schema:
            type: string
            pattern: '^act_\d+$'
            example: "906594379912215"
        - name: date_preset
          in: query
          description: Período predefinido para análise
          schema:
            type: string
            enum: [today, yesterday, last_3d, last_7d, last_30d, this_month, last_month]
            default: "last_7d"
        - name: breakdowns
          in: query
          description: Breakdowns para análise detalhada (máximo 2-3)
          schema:
            type: string
            example: "publisher_platform,platform_position"
      responses:
        '200':
          description: Success
          headers:
            X-Business-Use-Case-Usage:
              $ref: "#/components/headers/BusinessUseCaseUsage"
            X-Rate-Limit-Reset:
              $ref: "#/components/headers/RateLimitReset"
            Cache-Control:
              $ref: "#/components/headers/CacheControl"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InsightsResponse"
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/Unauthorized"
        '429':
          $ref: "#/components/responses/RateLimitExceeded"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    InsightsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              date_start:
                type: string
                format: date
              date_end:
                type: string
                format: date
              publisher_platform:
                type: string
                example: "instagram"
              platform_position:
                type: string
                enum: [story, reel, feed]
              impressions:
                type: integer
                example: 13587
              reach:
                type: integer
                example: 11145
              spend:
                type: number
                example: 243.78
              ctr:
                type: number
                example: 18.43
              cpc:
                type: number
                example: 0.10
              video_p25_watched_actions:
                type: integer
                example: 800
              video_p50_watched_actions:
                type: integer
                example: 600
              video_p75_watched_actions:
                type: integer
                example: 400
              video_p95_watched_actions:
                type: integer
                example: 200
              video_avg_time_watched_actions:
                type: number
                example: 3.0

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Unauthorized:
      description: Invalid or expired access token
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    RateLimitExceeded:
      description: Rate limit exceeded
      headers:
        Retry-After:
          schema:
            type: integer
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  headers:
    BusinessUseCaseUsage:
      description: Usage stats for business use case
      schema:
        type: string
    RateLimitReset:
      description: Time until rate limit reset in seconds
      schema:
        type: integer
    CacheControl:
      description: Cache control directives
      schema:
        type: string
