openapi: 3.1.0
info:
  title: Meta Marketing API
  description: |
    Meta Marketing API for campaign management and insights.
    Rate limits and best practices are enforced.
  version: '22.0'
  x-rate-limiting:
    standard-tier:
      points: 9000
      window: 300
      block: 60
    development-tier:
      points: 60
      window: 300
      block: 300
  x-performance:
    cache-ttl: 300
    timeout:
      sync: 30
      async: 3600
    compression: true
    batch-size: 100

servers:
  - url: https://graph.facebook.com/v22.0
    description: Meta Graph API v22.0

security:
  - bearerAuth: []

paths:
  /102264027940184:
    $ref: "./paths/getPageAccessToken.yaml#/paths/getPageAccessToken"
  /act_906594379912215/campaigns:
    $ref: "./paths/getCampaigns.yaml#/paths/getCampaigns"
  /{campaign_id}:
    $ref: "./paths/getCampaignById.yaml#/paths/getCampaignById"
  /act_906594379912215/insights:
    $ref: "./paths/getCampaignInsights.yaml#/paths/getCampaignInsights"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Meta API Access Token

  headers:
    $ref: "./components/headers.yaml#/headers"

  responses:
    $ref: "./components/responses.yaml#/responses"

  schemas:
    $ref: "./components/schemas.yaml#/schemas"
